services:
  dataset_log:
    build: .
    container_name: dataset_log
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: python backup_datasets.py

