name: Daily Open Data Dataset Download

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Download CSV file
        run: |
          python download_dataset.py
        env:
          DATASET: ${{ secrets.DATASET }}
          RESOURCE: ${{ secrets.RESOURCE }}
          SERVICE: ${{ secrets.SERVICE }}

      - name: Commit and push the file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ${{ secrets.SERVICE }}.csv
          git commit -m "Update ${{ secrets.SERVICE }}.csv"
          git push

