name: Daily Open Data Dataset Download

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "SERVICES=${{ secrets.SERVICES }}" > .env

      - name: Download and Save CSV files
        run: docker compose -f docker-compose.yaml up --build -d

      - name: Commit and push the files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./services/*.csv
          git commit -m "Daily dataset backup."
          git push
